### ISSUE TITLE
ギリシャ文字やキリル文字が見やすいようにフォント設定を変える

### ISSUE THREAD

**Issue by huideyeren** [syuilo/Misskey#10192]
## Summary

現行のMisskeyのフォントは以下のようになっています。

``` scss
html {
  font-family: 'Hiragino Maru Gothic Pro', "BIZ UDGothic", Roboto, HelveticaNeue, Arial, sans-serif;
}
```

この状態でギリシャ文字やキリル文字のような[East Asian Width](https://ja.wikipedia.org/wiki/%E6%9D%B1%E3%82%A2%E3%82%B8%E3%82%A2%E3%81%AE%E6%96%87%E5%AD%97%E5%B9%85)では文字幅が曖昧な文字を表示させると「いい感じ」には表示してくれません。

とりわけ、ウクライナ語を表示しようとすると全角と半角が入り交じって結構見た目が不自然になります。

なので、MisskeyのデフォルトフォントをGoogle Fontsを使って拡張ラテン文字や拡張ギリシャ文字、拡張キリル文字を含むフォントと日本語フォントを混植するようにしても良いと思います。

あと、韓国語も同様に混植で対応すればいい感じの表示ができそうです。

このフォント設定がよさそうです。

``` css
@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+KR:wght@300;400;500;700&family=Noto+Sans+JP:wght@300;400;500;700&family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap');

html {
  font-family: 'Ubuntu', 'IBM Plex Sans KR', 'Noto Sans JP', sans-serif;
}
```
