### ISSUE TITLE
ERR Invalid stream ID specified as stream command argument

### ISSUE THREAD

**Issue by willin** [syuilo/Misskey#10777]
## 💡 Summary

ref #10464 

## 🤬 Actual Behavior

```js
{
	"error": {
		"message": "Internal error occurred. Please contact us if the error persists.",
		"code": "INTERNAL_ERROR",
		"id": "5d37dbcb-891e-41ca-a3d6-e690c97775ac",
		"kind": "server",
		"info": {
			"e": {
				"message": "ERR Invalid stream ID specified as stream command argument",
				"code": "ReplyError",
				"id": "a1d1c243-1e92-4788-a553-1376d57c2697"
			}
		}
	}
}
```

## 📌 Environment

Misskey version:  docker misskey/misskey:latest
Your OS: MacOS latest
Your browser: Brave latest

Nginx:

```nginx
# For WebSocket
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

proxy_cache_path /tmp/nginx_cache levels=1:2 keys_zone=cache1:16m max_size=1g inactive=720m use_temp_path=off;

server {
    listen 80;
    listen [::]:80;
    server_name log.lu www.log.lu;
    # Change to your upload limit
    client_max_body_size 100m;

    # Proxy to Node
    location / {
        proxy_pass http://misskey:3000;
        proxy_set_header Host $host;
        proxy_http_version 1.1;
        proxy_redirect off;

        # If it's behind another reverse proxy or CDN, remove the following.
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;

        # For WebSocket
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;

        # Cache settings
        proxy_cache cache1;
        proxy_cache_lock on;
        proxy_cache_use_stale updating;
        proxy_force_ranges on;
        add_header X-Cache $upstream_cache_status;
    }
}
```

docker compose file:

```yml

version: "3"

services:
  web:
    restart: always
    image: misskey/misskey:latest
    container_name: misskey_web
    links:
      - db
      - redis
    ports:
      - "3001:3001"
    networks:
      - internal_network
      - external_network
    volumes:
      - ./config:/misskey/.config:ro
      - ./files:/misskey/files 

  redis:
    restart: always
    image: redis:7-alpine
    container_name: misskey_redis
    networks:
      - internal_network
    volumes:
      - ./redis:/data

  db:
    restart: always
    image: postgres:12.2-alpine
    container_name: misskey_db
    networks:
      - internal_network
    env_file:
      - ./config/docker.en
    volumes:
      - ./db:/var/lib/postgresql/data

networks:
  internal_network:
    internal: true
  external_network:
 ```
