### ISSUE TITLE
Misskey WebのCPU使用率が異常に高い

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#10805]
Chromeの開発者ツールでパフォーマンス計測してもそこには負荷は表れないのにOS側のタスクマネージャーなどで確認するとMisskey Webを開いている間だけ異常にCPU使用率が高い

- シークレットモードでも再現するので拡張機能が影響しているとかではない
- 前述したようにパフォーマンス計測ツールでは異常がないためJavaScript、Vueなどの問題ではないと思われる(CSSとか？)
- ストリーミングをオフにし、タイムラインなどの更新が無い状態でも変わらずCPU使用率が高い
- ブラーエフェクトやアニメーションを無効にしても変わらず
- タブ切り替えなどで画面が表示されていない状態だとCPU負荷が上がらない

解決した方に報奨金を進呈

Chromeで確認

**Comment by fruitriin** [comment]
相対時間の計算タイマーがたくさんたまってるかも

**Comment by syuilo** [comment]
setInterval/setTimeoutって低頻度だったとしてもそれなりの数あると割と高負荷になるのかしらね

**Comment by syuilo** [comment]
related https://github.com/misskey-dev/misskey/pull/10547

**Comment by syuilo** [comment]
> setInterval/setTimeoutって低頻度だったとしてもそれなりの数あると割と高負荷になるのかしらね

実験してみるか

**Comment by fruitriin** [comment]
もしタイマーが原因なら Intersection Observerで画面外のやつはタイマー止めていくとよさそう
あとは理想をいえば画面外のDOMはVertial DOMにして実際にレンダリングしないようにすればDOMのレンダリングによるメモリ圧迫は避けられるけど

**Comment by syuilo** [comment]
> > setInterval/setTimeoutって低頻度だったとしてもそれなりの数あると割と高負荷になるのかしらね
> 
> 実験してみるか

1万回setIntervalしてタイマー作ってみたけど全く負荷は上がらなかったから違いそう

**Comment by acid-chicken** [comment]
> > > setInterval/setTimeoutって低頻度だったとしてもそれなりの数あると割と高負荷になるのかしらね
> > 
> > 実験してみるか
> 
> 1万回setIntervalしてタイマー作ってみたけど全く負荷は上がらなかったから違いそう

中の処理がからなら実験の意味あんまりなさそう

**Comment by yuriha-chan** [comment]
猫耳のアニメーションに起因する描画処理が定期的に発火してるっぽい

**Comment by syuilo** [comment]
それは確認できるけどCPUめちゃくちゃ使うほどかなと思っている

**Comment by syuilo** [comment]
あと少し前にMkAvatarレンダリングしない状態でテストしたときは負荷が変わらなかった

**Comment by yuriha-chan** [comment]
なるほど
タブ切り替えなどで画面が表示されていない状態だとCPU負荷が上がらないので画面更新関連の負荷ではありそう
あと私の環境ではプロファイラ上でMkTooltip関連の処理が重い（なんで発火しているかはわからない）

**Comment by syuilo** [comment]
> タブ切り替えなどで画面が表示されていない状態だとCPU負荷が上がらない

これはたしかに

> 画面更新関連の負荷ではありそう

タブが隠れている状態だとJSの実行が制限されたりいろいろ状態が異なるから一概に画面更新関連の負荷とは言えなそう

**Comment by syuilo** [comment]
ローカル環境でDeckUIにしてタイムライン大量に開いた状態でいろいろテストしてみた
- MkTimeを空のコンポーネントに置き換え → 効果なし
- MkAvatarを空のコンポーネントに置き換え → 50%くらい減ったかも(追試中)

**Comment by syuilo** [comment]
# バニラ
![normal](https://github.com/misskey-dev/misskey/assets/4439005/92abab45-d20a-425a-9ae5-52dd6fb36c40)

# アバターなし
![noavatars](https://github.com/misskey-dev/misskey/assets/4439005/ef4caa2d-f2e1-49e8-a90e-8f556a3daf84)

**Comment by syuilo** [comment]
MkAvatarのレンダリングをしないと、かなり負荷が減ることが分かった

**Comment by syuilo** [comment]
また、MkAvatarのレンダリングをする場合でも、以下のCSSを削除した場合でもレンダリングしない場合と同じくらい負荷が減ることが分かった
``` scss
		&.mask {
			-webkit-mask:
				url('data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><filter id="a"><feGaussianBlur in="SourceGraphic" stdDeviation="1"/></filter><circle cx="16" cy="16" r="15" filter="url(%23a)"/></svg>') center / 50% 50%,
				linear-gradient(#fff, #fff);
			-webkit-mask-composite: destination-out, source-over;
			mask:
				url('data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><filter id="a"><feGaussianBlur in="SourceGraphic" stdDeviation="1"/></filter><circle cx="16" cy="16" r="15" filter="url(%23a)"/></svg>') exclude center / 50% 50%,
				linear-gradient(#fff, #fff); // polyfill of `image(#fff)`

			> .earLeft {
				animation: eartightleft 6s infinite;
			}

			> .earRight {
				animation: eartightright 6s infinite;
			}
		}
```
![image](https://github.com/misskey-dev/misskey/assets/4439005/d05bc109-c567-4a1d-88a8-784178eda7b1)
