### ISSUE TITLE
Scrolling Issue in Safari for Top and Bottom Bars

### ISSUE THREAD

**Issue by caipira113** [syuilo/Misskey#10977]
## 💡 Summary
After the Misskey update, scrolling is now possible in the areas where it was previously disabled in Safari.

## 🥰 Expected Behavior
Scrolling should be disabled when trying to scroll within the top and bottom bars.

## 🤬 Actual Behavior
Scrolling is possible within the top and bottom bar areas.
<video alt="issues-video" src="https://github.com/misskey-dev/misskey/assets/54402969/65e45beb-b0a0-4dfa-abe7-ddbfa6ac9fa3" controls></video>
[video](https://github.com/misskey-dev/misskey/assets/54402969/65e45beb-b0a0-4dfa-abe7-ddbfa6ac9fa3)

## 📝 Steps to Reproduce
1. Update Misskey to version 13.13.0+.
2. Attempt to scroll by holding and dragging the top or bottom bars in Safari.

### 💻 Frontend
* Model and OS of the device(s): iPhone 13 iOS 16.5
* Browser: Safari 16.5
* Server URL: stella.place

### 🛰 Backend (for instance admin)
* Misskey: 13.13.1
* Node: 18.16.0

**Comment by syuilo** [comment]
Discordも非bodyスクロールだったけどこういう問題は発生しなかったわね
どういう実装なんだろう

**Comment by syuilo** [comment]
調べた感じDiscordは最上位要素(Misskeyでいう#misskey_app)をposition: absoluteにしててそれが効いてるのかも

**Comment by syuilo** [comment]
memo
```
.xApN7 {
  overscroll-behavior: none;
}
```

**Comment by syuilo** [comment]
> 調べた感じDiscordは最上位要素(Misskeyでいう#misskey_app)をposition: absoluteにしててそれが効いてるのかも

関係ないかも

**Comment by syuilo** [comment]
```css
html,
body {
  width: 100%;
  height: 100%;
  overflow: clip;
  position: fixed;
  top: 0;
  left: 0;
}

#misskey_app {
  width: 100%;
  height: 100%;
  overflow: clip;
  position: absolute;
  top: 0;
  left: 0;
}
```
で解決した
