### ISSUE TITLE
Redisにユーザー名とパスコード入力を強要する設定の場合にMisskeyが対応できない

### ISSUE THREAD

**Issue by waya0125** [syuilo/Misskey#11082]
## Summary

現状、Misskeyで使用しているライブラリはパスコードとユーザーの指定に対応しているが、Misskey側のコンフィグが対応していないためpassだけ指定しても`
WRONGPASS invalid username-password pair or user is disabled`とエラーを吐かれてしまう
下記のような形でConfigができると非常に嬉しい。
```
redis:
  host: HOSTNAME
  port: PORT
  user: USERNAME
  pass: PASSCODE
  ```
  
当方の環境
| 概要 | 説明 |
| :--- | :--- |
| OS | Ubuntu Server 22.04.2 LTS x86_64 |
| Kernel | 5.15.0-73-generic |
| Nginx | nginx/1.18.0 (Ubuntu) |
| Redis Server | v=7.0.11 sha=00000000:0 malloc=jemalloc-5.2.1 bits=64 build=3af367a78d5e21e9 |

今のところ、既存のRedisと共存することができないためポートを変更してDockerを用いてRedisを作ってそこに作ってます。
