### ISSUE TITLE
自分が押したリアクションのデザイン改善案

### ISSUE THREAD

**Issue by EbiseLutica** [syuilo/Misskey#11272]
* 既存のUIだと、テーマのアクセントカラーによって絵文字が見えづらい
* accentedBgを使うことで、ダークテーマ・ライトテーマ両方に最低限配慮した絵文字であれば表示を改善できそう

### 問題となる例

<img width="239" alt="image" src="https://github.com/misskey-dev/misskey/assets/7106976/5f767131-61c2-47a1-ad53-0cad980e193d">

### 改善例

<img width="241" alt="image" src="https://github.com/misskey-dev/misskey/assets/7106976/b6afe2b8-01fd-4ca4-b923-0e86985ad084">

なお、以下のカスタムCSSで再現できます。

```css
.xDRXD.x9Z4v, .xDRXD.x9Z4v:hover {
    background: var(--accentedBg) !important;
    color: var(--accent) !important;
    border: 1px solid var(--accent) !important;
}

.xDRXD.x9Z4v>.xDpSv {
    color: var(--accent) !important;
}
```
