### ISSUE TITLE
unable to create initial admin user on docker-compose install using docker hub images: Could not find any entity of type "UserProfile" ...

### ISSUE THREAD

**Issue by eyduh** [syuilo/Misskey#11310]
## 💡 Summary

Can´t get past create admin user screen on fresh docker compose install

## 🥰 Expected Behavior

Admin user is created and I am forwarded to the next step

## 🤬 Actual Behavior

Error when user is first created. if I try again with the same user name I get that user name is already used in the logs.

![image](https://github.com/misskey-dev/misskey/assets/29815625/39d2ab7e-6669-4d5e-83eb-3760acae4761)

## 📝 Steps to Reproduce

1. Install using docker-compose.yml with docker hub image (tested with latest stable 13.13.2 and latest beta 13.14.0-beta.5 as of writing)
2. wait for database to initialize and "DONE *  [core boot]     Misskey initialized. Starting 1 worker."
3. setup reverse proxy to point to the misskey-web-1 container and published port
4. try to make user through public https://misskey.URL.tld or directly using http://hostname:3000

## 📌 Environment

Linux 6.1.11-meson64 (aarch64), Alpine linux 3.18 LXD container on proxmox-aarch64 host.

`docker-compose.yml`
```yml
version: "3"

services:
  web:
    image: misskey/misskey:13.14.0-beta.5
    restart: always
    links:
      - db
      - redis
#     - meilisearch
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "3000:3000"
    networks:
      - internal_network
      - external_network
    volumes:
      - ./files:/misskey/files
      - ./.config:/misskey/.config:ro

  redis:
    restart: always
    image: redis:7-alpine
    networks:
      - internal_network
    volumes:
      - ./redis:/data
    healthcheck:
      test: "redis-cli ping"
      interval: 5s
      retries: 20

  db:
    restart: always
    image: postgres:15-alpine
    networks:
      - internal_network
    env_file:
      - .config/docker.env
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
      interval: 5s
      retries: 20

#  meilisearch:
#    restart: always
#    image: getmeili/meilisearch:v1.1.1
#    environment:
#      - MEILI_NO_ANALYTICS=true
#      - MEILI_ENV=production
#    env_file:
#      - .config/meilisearch.env
#    networks:
#      - internal_network
#    volumes:
#      - ./meili_data:/meili_data

networks:
  internal_network:
    internal: true
  external_network:

```

### 💻 Frontend
* Model and OS of the device(s):
NixOS 23.05, thinkpad
* Browser:
firefox 114.0.2
* Misskey:
  13.13.2 / 13.14.0-beta.5

### 🛰 Backend (for server admin)

* Installation Method or Hosting Service: 
* Misskey: 13.13.2 / 13.14.0-beta.5
* Node: 20.3.1
* PostgreSQL: 15.3
* Redis: 7.x.x
* OS and Architecture: Alpine linux 3.18 LXD container on Proxmox aarch64 host 

```
ERR  *  [api]   Internal error occurred in admin/accounts/create: Could not find any entity of type "UserProfile" matching: {
    "userId": "9hbnppkie9"
}
{
  ep: 'admin/accounts/create',
  ps: { username: 'testing12', password: 'test password-lol' },
  e: {
    message: 'Could not find any entity of type "UserProfile" matching: {\n' +
      '    "userId": "9hbnppkie9"\n' +
      '}',
    code: 'EntityNotFoundError',
    stack: 'EntityNotFoundError: Could not find any entity of type "UserProfile" matching: {\n' +
      '    "userId": "9hbnppkie9"\n' +
      '}\n' +
      '    at /misskey/node_modules/.pnpm/typeorm@0.3.17_ioredis@5.3.2_pg@8.11.1/node_modules/typeorm/entity-manager/EntityManager.js:651:39\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
      '    at async UserEntityService.pack (file:///misskey/packages/backend/built/core/entities/UserEntityService.js:259:59)\n' +
      '    at async file:///misskey/packages/backend/built/server/api/endpoints/admin/accounts/create.js:69:25\n' +
      '    at async ApiCallService.call (file:///misskey/packages/backend/built/server/api/ApiCallService.js:315:16)',
    id: 'a0bbfdef-4ef6-47f3-98de-81b98f30f11c'
  }
}
EntityNotFoundError: Could not find any entity of type "UserProfile" matching: {
    "userId": "9hbnppkie9"
}
    at /misskey/node_modules/.pnpm/typeorm@0.3.17_ioredis@5.3.2_pg@8.11.1/node_modules/typeorm/entity-manager/EntityManager.js:651:39
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async UserEntityService.pack (file:///misskey/packages/backend/built/core/entities/UserEntityService.js:259:59)
    at async file:///misskey/packages/backend/built/server/api/endpoints/admin/accounts/create.js:69:25
    at async ApiCallService.call (file:///misskey/packages/backend/built/server/api/ApiCallService.js:315:16) a0bbfdef-4ef6-47f3-98de-81b98f30f11c


```
