### ISSUE TITLE
スクラッチパッドが正しく表示されない Scratchpad doesn't render correctly

### ISSUE THREAD

**Issue by MineCake147E** [syuilo/Misskey#12398]
### 💡 Summary

スクラッチパッドが正しく表示されません。
![image](https://github.com/misskey-dev/misskey/assets/31585494/285c8647-4ced-4b75-ae1c-e83ea9020490)

少し調べてみたところ、入力用の`textarea`が正しくリサイズされていないようです。
![image](https://github.com/misskey-dev/misskey/assets/31585494/64d35fa8-4adb-447d-8945-13e618afe6bf)

<details><summary>回避策(off-topic?)</summary>

回避策として、以下のカスタムCSSを使っています。
```css
.xuT74 {
    min-width: calc(100% - 24px);
    height: calc(100% - 24px);
    margin: 0;
    overflow: hidden;
    padding-bottom: 24px !important;
}

.xxhr0, .xuT74, code, code * {
    font-family: monospace !important;
}
.xuFXM * {
    line-height: 1.1em !important;
    margin-bottom: 12px;
}
.xmqOk {
    background-color: #1E1E1E;
    scrollbar-color: var(--acrylicBg) transparent;
}
```
![image](https://github.com/misskey-dev/misskey/assets/31585494/88315559-d6f9-4bc5-9adc-da64e3c31864)

</details>

### 🥰 Expected Behavior

スクラッチパッドが正しく表示される

### 🤬 Actual Behavior

スクラッチパッドが正しく表示されない

### 📝 Steps to Reproduce

1. スクラッチパッドを開く
2. 三行以上かつ先頭行がその末尾が見えなくなるくらい長いテキストを入力する
3. 入力したテキストを選択する
4. 観察する

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
  - PC: Custom built PC
    - OS: Windows 11 Home 22H2 (22621.2715)
    - CPU: Intel(R) Xeon(R) w5-2455X   3.19 GHz
    - RAM: 32 GB DDR5 ECC RDIMM
    - Graphics: NVIDIA GeForce GTX1060(6 GB)
    - Storage: 
      - OS(C:) : WD_BLACK SN770 1TB PCIe 4.0 NVMe M.2 SSD
      - DATA (D:) : Western Digital WDC WD10EZEX-22MFCA0 1000.2 GB 7200RPM SATA HDD
      - WORKSPACE (E:) : Seagate ST1000DM003-1ER162 1000.2 GB 7200RPM SATA HDD
* Browser: Mozilla Firefox 119.0.1
* Server URL: misskey.io
* Misskey: 2023.11.1-io.0c
```
