### ISSUE TITLE
「投稿されてから時間が経過しているノートであることを視覚的に分かりやすく」を無効化させてほしい

### ISSUE THREAD

**Issue by anatawa12** [syuilo/Misskey#12583]
### Summary

21986a2168d9c13725daef71ac8fd9722ee0fa91 をoptionalにしてほしいです

### Purpose

とくにwarn色のときにシンプルに日時が読みづらいです。
また、アンテナとかで並んでるときにまぁまぁ目障りです

**Comment by kanade** [comment]
カスタムCSSで変更することはできそうです
```css
.x82N4 {
    color: inherit;
}

.x82N4.xf65g {
    color: inherit;
}
```
