### ISSUE TITLE
検索機能をpgroongaに対応させる

### ISSUE THREAD

**Issue by samunohito** [syuilo/Misskey#14730]
### Summary

[pgroonga](https://pgroonga.github.io/ja/)に対応し、

- 既存の組み込み検索
- Meilisearchを使用しての検索
- pgroongaを使用しての検索

…を選べるようにします。

### Purpose

Meilisearchを採用していないサーバ向けに検索機能増強の選択肢を提供できる

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

---

EDIT:

⚠️⚠️重要⚠️⚠️  
`2025.1.0`以降、`.config/default.yml`に全文検索のプロバイダ設定が追加となりました。  
**既に運用されているMisskeyサーバでMeilisearchを使用している場合は特にご注意願います！**  

以前のバージョンでは`meilisearch`の接続情報などを設定することでMeilisearchが有効になっていましたが、
上記に加えて全文検索のプロバイダ設定を行わないとMeilisearchを利用出来ません。

### 新しい設定項目について

`2025.1.0` より、設定ファイル（`.config/default.yml`）に以下の全文検索プロバイダの設定項目が追加されます。

```yml
#   ┌───────────────────────────────┐
#───┘ Fulltext search configuration └─────────────────────────────

# These are the setting items for the full-text search provider.
fulltextSearch:
  # You can select the ID generation method.
  # - sqlLike (default)
  #   Use SQL-like search.
  #   This is a standard feature of PostgreSQL, so no special extensions are required.
  # - sqlPgroonga
  #   Use pgroonga.
  #   You need to install pgroonga and configure it as a PostgreSQL extension.
  #   In addition to the above, you need to create a pgroonga index on the text column of the note table.
  #   see: https://pgroonga.github.io/tutorial/
  # - meilisearch
  #   Use Meilisearch.
  #   You need to install Meilisearch and configure.
  provider: sqlLike
```

この設定は、ノート検索時に使用する全文検索プロバイダを指定するためのものです。以下に設定可能な値を説明します。

- sqlLike (デフォルト)
PostgreSQLの標準的なLIKE句を使用して検索を行います。pg_bigmを利用する場合もこの設定を選択してください。

- sqlPgroonga
PostgreSQLの拡張機能「pgroonga」を使用して検索を行います。
pgroongaのインストールおよび設定が必要です。また、noteテーブルのtext列にpgroongaインデックスを作成する必要があります。詳細は[公式チュートリアル](https://pgroonga.github.io/tutorial/)をご参照ください。

- meilisearch
Meilisearchを使用して検索を行います。Meilisearchのインストールと設定が必要です。

---

さらにEDIT:

- 下記理由からpgroongaのindexを付与するマイグレーションsqlを作成していません
  - pgroongaはPostgreSQLの拡張機能であり、デフォルトでは存在しないものである
  （インストールしてPostgreSQLに認識させないとインデックスを作れない）
  - マイグレーションsqlの中でpgroongaの導入有無を判定するのはちょっと現実的ではない
- 導入する場合、下記のようなSQLを手動実行してindexを作成いただく必要があります。
```sql
create index idx_note_text_with_pgroonga on note using pgroonga (text);
```
