### ISSUE TITLE
Follow Activityに対してstringでAccept/Rejectを受け取った場合に詰んでしまう

### ISSUE THREAD

**Issue by mei23** [syuilo/Misskey#8218]
## 💡 Summary

Misskey sends
```yml
  id: https://local/:uuid ★random id
  type: Follow
  actor: https://local/users/follower
  object: https://remote/users/followee
```

Misskey receives... This is OK 
```yml
  type: Accept
  actor: https://remote/users/followee
  object:
    id: https://local/:uuid ★random id
    type: Follow
    actor: https://local/users/follower
    object: https://remote/users/followee
```

Suppose you receive this, This is valid. But unable to perform processing.
```yml
  type: Accept
  actor: https://remote/users/followee
  object: https://local/:uuid ★random id
```

#8165

## 📝 Steps to Reproduce

1.
2.
3.
