### ISSUE TITLE
Mobile UI bottom bar design

### ISSUE THREAD

**Issue by ThatOneCalculator** [syuilo/Misskey#8754]
## Summary

I personally feel the current bottom bar on mobile is a bit clunky to look at and use, especially when blur is off. Here's a design I came up (definitally inspired by Material Design 3) with to make it feel a bit more modern. I'd love some thoughts and feedback.

## Screenshot

<img src="https://user-images.githubusercontent.com/44733677/170847522-ebcdbdbc-9eb9-4f19-9851-ce0c985caefe.png" height="600"/>

## Injected CSS

This is a very hacky way of doing it, just for demonstration purposes.

```css
.buttons {
    height: 80px;
    /* This should be the regular bg color */
    background: #191724 !important;
}

.nav, .home, .notifications, .widget {
    height: 35px !important;
    left: 40px !important;

}

.post {
    transform: translate(0px, -90px) !important;
    /* This should be a theme color */
    background: #6e6a86 !important;
}
```
