### ISSUE TITLE
Option to disable the notification indicator's blinking?

### ISSUE THREAD

**Issue by saschanaz** [syuilo/Misskey#9264]
## Summary

It blinks by default:

https://github.com/misskey-dev/misskey/blob/14221e78b7b98ffa93e15c211769a0e88be088e5/packages/client/src/ui/classic.header.vue#L163-L170

A CSS developer can disable this by:

```css
.notifications .indicator {
  animation: none !important;
}
```

But I don't see a way for non-developers to disable it. For some people (including me) it can be too distracting.
