### ISSUE TITLE
Misskey v13 failed to communicate with some of the mastodon sites and old misskey sites via relay

### ISSUE THREAD

**Issue by CHN-beta** [syuilo/Misskey#9752]
## 💡 Summary

After upgrade to v13, my Misskey instance failed to communicate with some of the other instances via relay. That is, for example, with misskey v13, most of the notes from `o3o.ca` no longer be shown in the global timeline, and the requests to `o3o.ca` showed a significant drop (red box in the picture).
![图片](https://user-images.githubusercontent.com/35858462/215367205-dff30593-f08b-4d61-acd3-64bb9f302ba8.png)

Meanwhile, old misskey instances (v12) could not communicate to v13 in a similar manner.

This behavior could be reproduced in a newly set instance.

## 🥰 Expected Behavior

All notes from mastodon and misskey v12 instances connected to the same relay should be shown in global timeline.

## 🤬 Actual Behavior

On a new set misskey v13 instances, a lot of notes from misskey v13 instances were shown in global timeline. No note from mastodon was shown.

On a new set misskey v12 instances, only notes from mastodon were shown in global timeline. Notes from misskey v12 instances might could also be shown in global timeline, but today active v12 instances are not common.

## 📝 Steps to Reproduce

1. Setup two new instance, use v12.119.2 and v13.2.5 respectively. The two instances use similar configs:
```
url: https://misskeytestv12.chn.moe/
port: 3004
db:
  host: 127.0.0.1
  port: 5432
  db: misskeytestv12
  user: xxx
  pass: xxxxxxxxxxxxxxx
  disableCache: true
  extra:
    statement_timeout: 600000
redis:
  host: localhost
  port: 6379
id: 'aid'
proxyRemoteFiles: true
signToActivityPubGet: true
```
2. Do not follow or search any one, Just add a relay: `https://relay.nya.one/inbox`
3. Wait for several minutes. In the global timeline of misskey v12 instance, only a lot of notes from mastodon was shown. In the global timeline of misskey v13 instance, only a lot of notes from misskey v13 was shown. 

A screenshot from v12 instance:

![图片](https://user-images.githubusercontent.com/35858462/215373231-387b3e1e-fdc1-4d5e-996a-5757158e1e55.png)

A screenshot from v13 instance:

![图片](https://user-images.githubusercontent.com/35858462/215373259-0d75638c-960e-4f6f-8b7e-4461eb5458da.png)

## 📌 Environment

Misskey version: 13.2.5, running with docker
Your OS: Gentoo
Your browser: firefox
